version: '3'
services:
  backend:
    networks:
    - apps
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

  frontend:
    networks:
    - apps
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

networks:
  apps: